### ISSUE TITLE
Failure in file transfer

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#104]
![image](https://cloud.githubusercontent.com/assets/79268/22156907/f01f2a72-defa-11e6-90cc-7c7b1221ca0a.png)

**Comment by robogen** [comment]
@CarrieBrown Could you detail what file/folder and hierarchy you were attempting to upload/download?

**Comment by CarrieBrown** [comment]
Of course, this happened when I switched to the file management screen. The home directory listed was blank (which it shouldn't be). The error (TypeError Cannot read property...) occurred when I clicked "Switch to work directory".

Additionally, I get an error (after this fact) when switching to the job management screen:
<img width="571" alt="screen shot 2017-01-20 at 10 29 18 am" src="https://cloud.githubusercontent.com/assets/13242287/22157062/af941458-defb-11e6-9209-d4fb73283cc8.png">

**Comment by djw8605** [comment]
@CarrieBrown That error in the screenshot is expected.  Stupid SVG error in visualization.

**Comment by CarrieBrown** [comment]
Ahh ok. Let me know if you want more info, I can attempt to recreate the situation.

**Comment by robogen** [comment]
@CarrieBrown what system do you use? Linux, Mac, Windows? Unless some other error occurred you should always have a home directory listed. Did you have a local and remote directory string listed?

**Comment by robogen** [comment]
@CarrieBrown Are you logging into Crane, Tusker, or which one?

**Comment by CarrieBrown** [comment]
I am running MacOS Sierra and I was logged into crane in this instance.

I am not sure what you mean by a local and remote directory string.

That screen opened in my home directory, but the files that exist in my home directory were not listed in the window.

**Comment by robogen** [comment]
@CarrieBrown could you do a screen shot of the file transfer page like that, before you click anything, and a screen shot of the console at the same point?

**Comment by CarrieBrown** [comment]
The only time I have been able to recreate the issue is by letting the connection time out. So I am guessing that the previous incident occurred when I lost connection to the cluster (at that time I had just logged in and was active so it was unexpected). But I will use the app on and off and let you know if it happens again.

Here are screenshots from the most recent time-out incident:
As I clicked to the file management screen:
![screen shot 2017-01-20 at 1 19 40 pm](https://cloud.githubusercontent.com/assets/13242287/22163518/c779c0b4-df18-11e6-87c1-3175697774ac.png)

As I clicked "Switch to work":
![screen shot 2017-01-20 at 1 19 48 pm](https://cloud.githubusercontent.com/assets/13242287/22163534/d8a0f43e-df18-11e6-9351-18d5c9d7113e.png)

**Comment by robogen** [comment]
@djw8605 @CarrieBrown This issue is part of detecting when authentication gets lost and the connection gets dropped, correct? We could probably close this issue, but I just ran into a new authentication issue accidentally. If you begin to login and give proper credentials, but then do nothing for a time (I'd say 2-3 min?) on the duo authentication window (1 for push notification, 2 for text, etc) then the connection hangs. But it has me stuck on the following screen with no options to try again
![hccgo_duo_lag](https://cloud.githubusercontent.com/assets/13003316/22570062/7c2ab28e-e95f-11e6-8518-375acb0b1af8.png)

**Comment by robogen** [comment]
Resolved by #107
