### ISSUE TITLE
For job submission, add option to save submission file

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#17]
I can envision the following use case:

1. Add a new option at the bottom of the job submission to save a submission configuration.
2. If the user clicks the submit, and the job isn't saved, ask the user if they wish to save the submission.

Save the submission configuration in a json file on the local machine.  I'm not sure where to save to.  Include a name to the submission configuration.  Also, give an option to load a saved submission.

In the future, we should provide a way to share submission configurations.

**Comment by adamfitzgibbon** [comment]
Would it be tacky to have different colored buttons? Right now I have the Submit and Cancel buttons as different colors and it looks alright, but I'm afraid that having four different colored buttons in the same form might be a little overwhelming.

**Comment by djw8605** [comment]
What if we re-thought the job submission just a little.  Think of this user workflow:

1. Goes to the submission page.  Lists options for submission:
   1. Load a previous submission that was saved.
   1. Create a new submission.
1. If it loads a saved submission, then go to normal submission form, but it should be pre-populated with the previous jobs data.
1. A new job submission is the same as current.

This would require adding a new intermediate page.

**Comment by adamfitzgibbon** [comment]
I like this method. Should the user be able to save multiple jobs and select them based on the job name?

**Comment by djw8605** [comment]
Yes, definitely be able to save multiple jobs.

**Comment by djw8605** [comment]
Hi @adamfitzgibbon 

Have you had a chance to work on this?

**Comment by adamfitzgibbon** [comment]
Yes, it's not completely finished yet but here's what I have so far:
![screen shot 2016-02-04 at 3 16 19 pm](https://cloud.githubusercontent.com/assets/8363569/12829954/4b230a28-cb52-11e5-8d9e-22b21e81a692.png)
Obviously it needs some work. My idea was to use a bootstrap accordion and have each panel-head display the jobname, date submitted, and Load button, and then the user could click on the head to see the exact job information. I was trying to make the entire panel-head clickable rather than just the link inside of it, but that had to be done by making the entire thing a button, which makes it hard to align the load button properly, thus the gross looking hangover. I was hoping to fix that today if you think this route is a good idea. So far the "Create New Job" button works and just pulls up the form as we have it in the current merge, and the json file is correctly being read and displayed in the panel-body.

**Comment by djw8605** [comment]
I think it looks great!  Few notes:

- It should have some words like 'click to expand' with arrows to indicate that it can be clicked on to show job details.
- It should have a cancel button, probably in the bottom left that should return it to the dashboard.
- The date text could be larger.

**Comment by adamfitzgibbon** [comment]
Okay I can add those, but a few clarifications:

I'm trying to think of where the instructional text would go where it would look okay. To the far right after the button (once it's on the same line)? And were you thinking of just the caret symbol that you used for the cluster selectize?

Should the date just be the same as the job name then? I was using the <small> tags to make it less pronounced than the name which I thought was more important. I could also keep the styling on it but adjust the font size to make it more readable.

**Comment by adamfitzgibbon** [comment]
Oh and also a question for probably a couple days in the future. What is the best way of transferring data between controllers? Does $scope persist between controllers? I'd probably just be sending the entire chosen job object through to populate the form with.

**Comment by djw8605** [comment]
Could the expand text be centered, below the title and date, and in it's own slightly grey'er box that spans the entire width of the box?

Make the date larger, but I like the styling otherwise.

As for data movement, yes, there is a $rootScope, but it should probably be used very infrequently.  Google around, there has to be a decent way to do that.

**Comment by adamfitzgibbon** [comment]
![screen shot 2016-02-04 at 4 33 24 pm](https://cloud.githubusercontent.com/assets/8363569/12832015/21c98bec-cb5d-11e5-921a-075c8b222826.png)

This is what I've gotten so far. For the most part I think it looks pretty good, but the name on the left not being aligned with the date and button on the right is bugging me, though I'm not sure why they would be misaligned that way. I'm still working on making the expand button a darker background color, as bootstrap doesn't seem to make it easy to alter the styling of their preset buttons and doesn't offer classes to darken the color slightly. Also, under this design, the user can only click where you see that outline in the first panel to open up the info, rather than the entire panel head like I was shooting for before. Not sure if that is a problem, but thought I'd just point that out.

**Comment by djw8605** [comment]
Everything that bugs you bugs me as well.  Keep working on it, this is certainly on the right trajectory!

**Comment by djw8605** [comment]
Go ahead and open a pull request, and feel free to continuously commit & push to that pull request, even if the fix isn't done.  That way I can test the code if needed.
