### ISSUE TITLE
File Transfer: Remote / Local swap

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#65]
Logically, Remote should be on the right, and local on the left.  Like reading a book, left to right.

And, they should be labled larger!

Agree?  Disagree?

**Comment by robogen** [comment]
Making the labeling bigger I could agree with, it's currently pretty standard in size. As for which is on which size, I'm not sure on that one. Being right-handed I have a stronger tendency to (when it comes to screens) begin looking on the right side of the screen and scan to the left. Also cause of that, it feels more comfortable to have 'local' and quickly needed things on my right where not-currently-needed but will soon be needed things to the left.

Otherwise yea, I'll definitely make that text bigger.

**Comment by djw8605** [comment]
What's the ordering of WinSCP, or FileZilla, or your favorite FTP Client?

**Comment by robogen** [comment]
Point taken, I'll make the swap

**Comment by djw8605** [comment]
Has this swap been made?

**Comment by robogen** [comment]
Not yet, I'm rolling it into the update to control file transfer functionality outside the controller of the page, so users can navigate away and come back to see exactly where they left off.
